-- Schedule Supabase Edge Function send-email-queue every 15 minutes.
-- Requires:
--   supabase secrets set EMAIL_QUEUE_SECRET=...
--   supabase secrets set RESEND_API_KEY=...
-- Also stores EMAIL_QUEUE_SECRET in Vault so pg_cron can call the function.

create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema extensions;
create extension if not exists supabase_vault;

-- Replace this value locally before running, or run the prepared command
-- generated by scripts/create-email-worker-secret.js.
-- select vault.create_secret('YOUR_EMAIL_QUEUE_SECRET', 'EMAIL_QUEUE_SECRET');

do $$
begin
  if exists (select 1 from cron.job where jobname = 'bstsxm-send-email-queue') then
    perform cron.unschedule('bstsxm-send-email-queue');
  end if;
end;
$$;

select cron.schedule(
  'bstsxm-send-email-queue',
  '*/15 * * * *',
  $$
  select net.http_post(
    url := 'https://npjkbhkmyfppmosforls.supabase.co/functions/v1/send-email-queue',
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-email-worker-secret', (
        select decrypted_secret
          from vault.decrypted_secrets
         where name = 'EMAIL_QUEUE_SECRET'
         limit 1
      )
    ),
    body := jsonb_build_object('batch_size', 25)
  );
  $$
);
